build:
	docker build -t alextanhongpin/kube-node .

run:
	docker run -p 8080:8080 -d alextanhongpin/kube-node

# build-local:
	# docker build -t 127.0.0.1:5000/alextanhongpin/kube-node .
	# docker push 127.0.0.1:5000/alextanhongpin/kube-node