apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  name: kubia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
    # Requires the pod to contain a label with the "app" key
    matchExpressions:
      - key: app
        operator: In # In, NotIn, Exists, DoesNotExist
        values:
          - kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: alextanhongpin/kube-node
        imagePullPolicy: IfNotPresent